import enum

class TableType(enum.Enum):
    INFOBOX="INFOBOX"
    FORMAT_BOX = "FORMAT_BOX"
    TOC ="TOC"
    WIKITABLE="WIKITABLE"
    SMALLTABLE="SMALL_TABLE"
    NO_CSS_CLASS = "NO_CSS_CLASS"
    INNER_TABLE = "INNER_TABLE"
    WITH_INNER_TABLE = "WITH_INNER_TABLE"
    WELL_FORMED = "WELL_FORMED"
    ILL_FORMED = "ILL_FORMED"
    USEFULL_TABLE="USEFULL_TABLE"
